# ~/.tmuxinator/dev.yml

name: dev
root: ~/temp/pp

windows:
  - front:
      layout: main-vertical
      panes:
        - cd app/views;          vi .
        - cd app/static/css;     vi .
        - cd app/static/js/user; vi .
  - back:
      layout: main-horizontal
      panes:
        - cd app/routes;         vi routes.js
        - cd app/controllers;    vi .
        - cd app/models;         vi .
  - unit:
      layout: main-vertical
      panes:
        - cd test/unit;          vi .
        - npm test
  - accept:
      layout: main-vertical
      panes:
        - cd test/acceptance;    vi .
        - npm test
  - server: PORT=3333 DB=pp nodemon app/index.js
  - grunt: grunt
  - redis: clear; redis-cli
  - mongo: clear; mongo
  - grunt: grunt
  - system: htop
  - prompt1: clear
  - prompt2: clear

